config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :contributors
  resources :maintainers
  resources :repositories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  # Relations
  belongs_to :repository

end

app/models/maintainer.rb
class Maintainer < ApplicationRecord
end

app/models/repository.rb
class Repository < ApplicationRecord
  # Relations
  has_many :contributors

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_action :set_contributor, only: %i[ show edit update destroy ]

  # GET /contributors or /contributors.json
  def index
    @contributors = Contributor.all
  end

  # GET /contributors/1 or /contributors/1.json
  def show
  end

  # GET /contributors/new
  def new
    @contributor = Contributor.new
  end

  # GET /contributors/1/edit
  def edit
  end

  # POST /contributors or /contributors.json
  def create
    @contributor = Contributor.new(contributor_params)

    respond_to do |format|
      if @contributor.save
        format.html { redirect_to @contributor, notice: "Contributor was successfully created." }
        format.json { render :show, status: :created, location: @contributor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributors/1 or /contributors/1.json
  def update
    respond_to do |format|
      if @contributor.update(contributor_params)
        format.html { redirect_to @contributor, notice: "Contributor was successfully updated." }
        format.json { render :show, status: :ok, location: @contributor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributors/1 or /contributors/1.json
  def destroy
    @contributor.destroy
    respond_to do |format|
      format.html { redirect_to contributors_url, notice: "Contributor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contributor
      @contributor = Contributor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contributor_params
      params.require(:contributor).permit(:name, :repository_id)
    end
end

app/controllers/maintainers_controller.rb
class MaintainersController < ApplicationController
  before_action :set_maintainer, only: %i[ show edit update destroy ]

  # GET /maintainers or /maintainers.json
  def index
    @maintainers = Maintainer.all
  end

  # GET /maintainers/1 or /maintainers/1.json
  def show
  end

  # GET /maintainers/new
  def new
    @maintainer = Maintainer.new
  end

  # GET /maintainers/1/edit
  def edit
  end

  # POST /maintainers or /maintainers.json
  def create
    @maintainer = Maintainer.new(maintainer_params)

    respond_to do |format|
      if @maintainer.save
        format.html { redirect_to @maintainer, notice: "Maintainer was successfully created." }
        format.json { render :show, status: :created, location: @maintainer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maintainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintainers/1 or /maintainers/1.json
  def update
    respond_to do |format|
      if @maintainer.update(maintainer_params)
        format.html { redirect_to @maintainer, notice: "Maintainer was successfully updated." }
        format.json { render :show, status: :ok, location: @maintainer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maintainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintainers/1 or /maintainers/1.json
  def destroy
    @maintainer.destroy
    respond_to do |format|
      format.html { redirect_to maintainers_url, notice: "Maintainer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintainer
      @maintainer = Maintainer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintainer_params
      params.require(:maintainer).permit(:name, :references)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[ show edit update destroy ]

  # GET /repositories or /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1 or /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories or /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: "Repository was successfully created." }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1 or /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: "Repository was successfully updated." }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1 or /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: "Repository was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repository_params
      params.require(:repository).permit(:name, :version, :description, :url, :publisher)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/maintainers_helper.rb
module MaintainersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/contributors/_form.html.erb
<%= form_with(model: contributor) do |form| %>
  <% if contributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contributor.errors.count, "error") %> prohibited this contributor from being saved:</h2>

      <ul>
        <% contributor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :repository_id %>
    <%= form.text_field :repository_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contributors/edit.html.erb
<h1>Editing Contributor</h1>

<%= render 'form', contributor: @contributor %>

<%= link_to 'Show', @contributor %> |
<%= link_to 'Back', contributors_path %>

app/views/contributors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contributors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Repository</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contributors.each do |contributor| %>
      <tr>
        <td><%= contributor.name %></td>
        <td><%= contributor.repository_id %></td>
        <td><%= link_to 'Show', contributor %></td>
        <td><%= link_to 'Edit', edit_contributor_path(contributor) %></td>
        <td><%= link_to 'Destroy', contributor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contributor', new_contributor_path %>

app/views/contributors/new.html.erb
<h1>New Contributor</h1>

<%= render 'form', contributor: @contributor %>

<%= link_to 'Back', contributors_path %>

app/views/contributors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contributor.name %>
</p>

<p>
  <strong>Repository:</strong>
  <%= @contributor.repository_id %>
</p>

<%= link_to 'Edit', edit_contributor_path(@contributor) %> |
<%= link_to 'Back', contributors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RepositoriesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_pack_tag(params[:controller]) %>
  </body>
</html>

app/views/maintainers/_form.html.erb
<%= form_with(model: maintainer) do |form| %>
  <% if maintainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maintainer.errors.count, "error") %> prohibited this maintainer from being saved:</h2>

      <ul>
        <% maintainer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :references %>
    <%= form.text_field :references %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maintainers/edit.html.erb
<h1>Editing Maintainer</h1>

<%= render 'form', maintainer: @maintainer %>

<%= link_to 'Show', @maintainer %> |
<%= link_to 'Back', maintainers_path %>

app/views/maintainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maintainers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>References</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maintainers.each do |maintainer| %>
      <tr>
        <td><%= maintainer.name %></td>
        <td><%= maintainer.references %></td>
        <td><%= link_to 'Show', maintainer %></td>
        <td><%= link_to 'Edit', edit_maintainer_path(maintainer) %></td>
        <td><%= link_to 'Destroy', maintainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maintainer', new_maintainer_path %>

app/views/maintainers/new.html.erb
<h1>New Maintainer</h1>

<%= render 'form', maintainer: @maintainer %>

<%= link_to 'Back', maintainers_path %>

app/views/maintainers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @maintainer.name %>
</p>

<p>
  <strong>References:</strong>
  <%= @maintainer.references %>
</p>

<%= link_to 'Edit', edit_maintainer_path(@maintainer) %> |
<%= link_to 'Back', maintainers_path %>

app/views/pages/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-6">
      <input
         class="form-control"
         name="input-repository-search"
         id="input-repository-search"
         placeholder="react, highcharts, etc..."
         />
    </div>
  </div>
  <div class="row justify-content-md-center mt-5">
    <div class="col-md-6">
      <ul id="repository-list-container" class="list-group">
      </ul>
    </div>
  </div>
</div>

app/views/repositories/_form.html.erb
<%= form_with(model: repository) do |form| %>
  <% if repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
        <% repository.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :version %>
    <%= form.text_field :version %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Repositories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
      <th>Description</th>
      <th>Url</th>
      <th>Publisher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= repository.name %></td>
        <td><%= repository.version %></td>
        <td><%= repository.description %></td>
        <td><%= repository.url %></td>
        <td><%= repository.publisher %></td>
        <td><%= link_to 'Show', repository %></td>
        <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
        <td><%= link_to 'Destroy', repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form', repository: @repository %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Version:</strong>
  <%= @repository.version %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repository.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @repository.url %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @repository.publisher %>
</p>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>